---
openapi: 3.0.4
info:
  title: Fridgeventory
  version: 1.0.0
  description: |
    This in an app of registering pantry products.
    It stores what is remaining in the refrigerator.
components:
  schemas:
    User:
      type: object
      properties:
        username:
          description: Username to access the application
          type: string
        email:
          description: User email
          type: string
        password:
          description: User password
          type: string
      required:
      - username
      - email
      - password
    Pantryitem:
      type: object
      properties:
        name:
          description: product name
          type: string
        quantity:
          description: quantity of product
          type: number
        unit:
          description: unit of product
          type: string
        exp_date:
          description: Expiration date
          type: string
      required:
      - name
      - quantity
      - unit
      - exp_date
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
servers:
  url: /api
paths:
  /users/:
